from summa.summarizer import summarize
from summa import keywords

# texts
text1 = "Neo-Nazism consists of post-World War II militant social or political mo vements seeking to revive and implement the ideology of Nazism. Neo-Nazis seek t o employ their ideology to promote hatred and attack minorities, or in some case s to create a fascist political state. It is a global phenomenon, with organized representation in many countries and international networks. It borrows elements from Nazi doctrine, including ultranationalism, racism, xenophobia, ableism, hom ophobia, anti-Romanyism, antisemitism, anti-communism and initiating the Fourth Reich. Holocaust denial is a common feature, as is the incorporation of Nazi sym bols and admiration of Adolf Hitler. In some European and Latin American countri es, laws prohibit the expression of pro-Nazi, racist, anti-Semitic, or homophobi c views. Many Nazi-related symbols are banned in European countries (especially Germany) in an effort to curtail neo-Nazism. The term neo-Nazism describes any p ost-World War II militant, social or political movements seeking to revive the i deology of Nazism in whole or in part. The term neo-Nazism can also refer to the ideology of these movements, which may borrow elements from Nazi doctrine, inclu ding ultranationalism, anti-communism, racism, ableism, xenophobia, homophobia, anti-Romanyism, antisemitism, up to initiating the Fourth Reich. Holocaust denia l is a common feature, as is the incorporation of Nazi symbols and admiration of Adolf Hitler. Neo-Nazism is considered a particular form of far-right politics a nd right-wing extremism."
text2 = "In a quaint village lived Wille, a boy enchanted by computers and code. Determined to become the greatest programmer, he delved into learning, facing challenges head-on. With each triumph, his skills grew. Soon, Wille's name echoed in the programming world. His creations dazzled all. But Wille discovered true power lay in sharing knowledge. He founded a coding academy, inspiring others to follow their coding dreams. His legacy wasn’t just in skill but in the hearts he touched, proving that the most powerful programmers empower others."
text3Short = "In a realm veiled in mystic beauty, Svala ascended to rule, a vision of ethereal grace. Her silver hair cascaded like a waterfall, and her piercing gaze held the power to unravel reality itself. Under Svala's reign, an era of unprecedented harmony unfolded. Seasons pirouetted in choreographed elegance, crops flourished abundantly, and the creatures of the earth reveled in symbiotic bliss. Svala, a benevolent sovereign, walked among her people as both guide and protector. Her touch possessed healing magic, and her words echoed with the wisdom of forgotten prophecies. Architectural marvels adorned the cities she built, crowned with crystalline spires that reached for the heavens. Yet, the age of Svala faced challenges. Dark forces, envious of her dominion, attempted to disrupt the delicate balance she maintained. With a mere flick of her wrist, storms dispersed, and shadows fled. Svala, the enchanting ruler of a world draped in magic and wonder, left an indelible mark, a saga whispered by the winds and sung by the rivers for epochs to come."
text3Long = "Once, in a realm cloaked in mystic beauty, Svala, an enigmatic being of ancient power, ascended to rule the world. With silver hair cascading like a waterfall, she possessed a gaze that could pierce the veil of reality. Legends spoke of her wisdom, born from epochs of existence, and her benevolence that stretched across continents. Svala's reign was marked by an era of unprecedented harmony. She nurtured the land, weaving magic into the very fabric of nature. Under her rule, the seasons danced in choreographed elegance, crops flourished abundantly, and the creatures of the earth lived in symbiotic bliss. Yet, Svala was not a distant deity; she walked among her people, a guide and protector. Her touch healed wounds, and her words resonated with the echoes of forgotten prophecies. The cities she built were architectural marvels, adorned with crystalline spires that reached for the heavens. However, the age of Svala was not without its trials. Dark forces, jealous of her dominion, sought to challenge the delicate balance she maintained. Yet, with a flick of her wrist, storms dispersed, and shadows dissipated. Svala, the sovereign of a world draped in magic and wonder, etched her name into the very essence of existence, a saga whispered by the winds and sung by the rivers for epochs to come."
text4 = "The main problem with the term-frequency approach is that it scales up frequent terms and scales down rare terms which are empirically more informative than the high frequency terms. The basic intuition is that a term that occurs frequently in many documents is not a good discriminator. The important question here is: why would you in a classification problem emphasize a term which is almost present in the entire corpus of your documents? The tf-idf weight comes to solve these problems. What tf-idf gives is how important is a word to a document in a collection, and that’s why tf-idf incorporates local and global parameters. It takes in consideration not only a term isolated to a document but also the term within the document collection. What tf-idf does to solve that problem is to scale down the frequent terms while scaling up the rare terms; a term that occurs 10 times more than another isn’t 10 times more important than it, that’s why tf-idf uses the logarithmic scale to do that."

text = text4

# Define length of the summary as a proportion of the text
print("\nSummarize (ratio):")
print(summarize(text, ratio=0.3))

#print("\nSummarize (words):")
#print(summarize(text1, words=50))


print("\n\nKeywords:\n",keywords.keywords(text))
# to print the top 3 keywords
print("\n\nTop 3 Keywords:\n",keywords.keywords(text,words=3))
